const words = [
  {
    id: '5e9f5ee35eb9e72bc21af4a9',
    group: 0,
    page: 0,
    word: 'duck',
    image: 'files/01_0010.jpg',
    audio: 'files/01_0010.mp3',
    audioMeaning: 'files/01_0010_meaning.mp3',
    audioExample: 'files/01_0010_example.mp3',
    textMeaning: 'A <i>duck</i> is a small water bird.',
    textExample: 'People feed <b>ducks</b> at the lake.',
    transcription: '[dʌk]',
    textExampleTranslate: 'Люди кормят уток у озера',
    textMeaningTranslate: 'Утка - маленькая водяная птица',
    wordTranslate: 'утка',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a2',
    group: 0,
    page: 0,
    word: 'boat',
    image: 'files/01_0005.jpg',
    audio: 'files/01_0005.mp3',
    audioMeaning: 'files/01_0005_meaning.mp3',
    audioExample: 'files/01_0005_example.mp3',
    textMeaning: 'A <i>boat</i> is a vehicle that moves across water.',
    textExample: 'There is a small <b>boat</b> on the lake.',
    transcription: '[bout]',
    textExampleTranslate: 'На озере есть маленькая лодка',
    textMeaningTranslate:
      'Лодка - это транспортное средство, которое движется по воде',
    wordTranslate: 'лодка',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4af',
    group: 0,
    page: 0,
    word: 'typical',
    image: 'files/01_0016.jpg',
    audio: 'files/01_0016.mp3',
    audioMeaning: 'files/01_0016_meaning.mp3',
    audioExample: 'files/01_0016_example.mp3',
    textMeaning:
      'If something is <i>typical</i>, it is normal, or something that usually happens.',
    textExample: 'My <b>typical</b> breakfast is toast and eggs.',
    transcription: '[típikəl]',
    textExampleTranslate: 'Мой типичный завтрак - тост и яйца',
    textMeaningTranslate:
      'Если что-то типичное, это нормально, или что-то, что обычно происходит',
    wordTranslate: 'типичный',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a0',
    group: 0,
    page: 0,
    word: 'alcohol',
    image: 'files/01_0002.jpg',
    audio: 'files/01_0002.mp3',
    audioMeaning: 'files/01_0002_meaning.mp3',
    audioExample: 'files/01_0002_example.mp3',
    textMeaning:
      '<i>Alcohol</i> is a type of drink that can make people drunk.',
    textExample:
      'A person should not drive a car after he or she has been drinking <b>alcohol</b>.',
    transcription: '[ǽlkəhɔ̀ːl]',
    textExampleTranslate:
      'Человек не должен водить машину после того, как он выпил алкоголь',
    textMeaningTranslate:
      'Алкоголь - это тип напитка, который может сделать людей пьяными',
    wordTranslate: 'алкоголь',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b2',
    group: 0,
    page: 0,
    word: 'wine',
    image: 'files/01_0020.jpg',
    audio: 'files/01_0020.mp3',
    audioMeaning: 'files/01_0020_meaning.mp3',
    audioExample: 'files/01_0020_example.mp3',
    textMeaning: '<i>Wine</i> is an alcoholic drink made from grapes.',
    textExample: 'The store carried both red and white <b>wine</b>.',
    transcription: '[wain]',
    textExampleTranslate: 'В магазине было красное и белое вино',
    textMeaningTranslate: 'Вино - это алкогольный напиток из винограда',
    wordTranslate: 'вино',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a1',
    group: 0,
    page: 0,
    word: 'agree',
    image: 'files/01_0001.jpg',
    audio: 'files/01_0001.mp3',
    audioMeaning: 'files/01_0001_meaning.mp3',
    audioExample: 'files/01_0001_example.mp3',
    textMeaning:
      'To <i>agree</i> is to have the same opinion or belief as another person.',
    textExample: 'The students <b>agree</b> they have too much homework.',
    transcription: '[əgríː]',
    textExampleTranslate:
      'Студенты согласны, что у них слишком много домашней работы',
    textMeaningTranslate:
      'Согласиться - значит иметь то же мнение или убеждение, что и другой человек',
    wordTranslate: 'согласна',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4b1',
    group: 0,
    page: 0,
    word: 'weather',
    image: 'files/01_0018.jpg',
    audio: 'files/01_0018.mp3',
    audioMeaning: 'files/01_0018_meaning.mp3',
    audioExample: 'files/01_0018_example.mp3',
    textMeaning:
      '<i>Weather</i> is the temperature and the state of the outdoors.',
    textExample: 'Today’s <b>weather</b> is rainy and cloudy.',
    transcription: '[weðər]',
    textExampleTranslate: 'Сегодня погода дождливая и облачная',
    textMeaningTranslate: 'Погода это температура и состояние на улице',
    wordTranslate: 'погода',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a3',
    group: 0,
    page: 0,
    word: 'arrive',
    image: 'files/01_0003.jpg',
    audio: 'files/01_0003.mp3',
    audioMeaning: 'files/01_0003_meaning.mp3',
    audioExample: 'files/01_0003_example.mp3',
    textMeaning: 'To <i>arrive</i> is to get somewhere.',
    textExample: 'They <b>arrived</b> at school at 7 a.m.',
    transcription: '[əráiv]',
    textExampleTranslate: 'Они прибыли в школу в 7 часов утра',
    textMeaningTranslate: 'Приехать значит попасть куда-то',
    wordTranslate: 'прибыть',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4a5',
    group: 0,
    page: 0,
    word: 'breakfast',
    image: 'files/01_0006.jpg',
    audio: 'files/01_0006.mp3',
    audioMeaning: 'files/01_0006_meaning.mp3',
    audioExample: 'files/01_0006_example.mp3',
    textMeaning: '<i>Breakfast</i> is the morning meal.',
    textExample: 'I ate eggs for <b>breakfast</b>.',
    transcription: '[brekfəst]',
    textExampleTranslate: 'Я ел яйца на завтрак',
    textMeaningTranslate: 'Завтрак - это утренняя трапеза',
    wordTranslate: 'завтрак',
  },
  {
    id: '5e9f5ee35eb9e72bc21af4aa',
    group: 0,
    page: 0,
    word: 'enjoy',
    image: 'files/01_0011.jpg',
    audio: 'files/01_0011.mp3',
    audioMeaning: 'files/01_0011_meaning.mp3',
    audioExample: 'files/01_0011_example.mp3',
    textMeaning: 'To <i>enjoy</i> is to like something.',
    textExample: 'The woman <b>enjoys</b> riding her bicycle.',
    transcription: '[indʒɔ́i]',
    textExampleTranslate: 'Женщина любит кататься на велосипеде',
    textMeaningTranslate: 'Наслаждаться значит любить что-то',
    wordTranslate: 'наслаждаться',
  },
];

export type Word = typeof words[0];

export default words;
